#!/usr/bin/env python3
"""Generate supabase/03_seed_letters.sql from data/letters.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "data" / "letters.json"
OUT_PATH = ROOT / "supabase" / "03_seed_letters.sql"

# letters.json keys → friends.username in 02_seed.sql
USERNAME_MAP = {
    "mom": "momdad",
}


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    data = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    people = data.get("people") or {}
    copy = data.get("copy") or {}
    soundtrack = data.get("soundtrack") or {}

    lines: list[str] = [
        "-- Letters from Lorina — letter body + app settings",
        "-- AUTO-GENERATED by scripts/generate_supabase_seed.py",
        "-- Run AFTER 02_seed.sql in Supabase → SQL Editor.",
        "",
        "-- ============================================================",
        "-- app_settings (global copy + soundtrack)",
        "-- ============================================================",
        "insert into public.app_settings (key, value)",
        "values",
        f"  ('meta', {sql_str(json.dumps({'version': data.get('version'), 'brand': data.get('brand'), 'openingLine': data.get('openingLine')}, ensure_ascii=False))}::jsonb),",
        f"  ('copy', {sql_str(json.dumps(copy, ensure_ascii=False))}::jsonb),",
        f"  ('soundtrack', {sql_str(json.dumps(soundtrack, ensure_ascii=False))}::jsonb)",
        "on conflict (key) do update",
        "  set value = excluded.value,",
        "      updated_at = now();",
        "",
        "-- ============================================================",
        "-- letter bodies (matched by friend username = letters.json key)",
        "-- ============================================================",
    ]

    for json_key, person in people.items():
        username = USERNAME_MAP.get(json_key, json_key)
        letter = person.get("letter") or {}
        board = person.get("scratchboard") or {}
        paragraphs = letter.get("paragraphs") or []
        board_json = json.dumps(board, ensure_ascii=False)
        paras_json = json.dumps(paragraphs, ensure_ascii=False)
        locked = json_key != "adi"

        lines.extend(
            [
                f"-- {json_key} → friends.username = {username}",
                "update public.letters l",
                "set",
                f"  title = {sql_str(person.get('title') or 'A letter')},",
                f"  greeting = {sql_str(person.get('greeting') or '')},",
                f"  opener = {sql_str(letter.get('opener') or '')},",
                f"  paragraphs = {sql_str(paras_json)}::jsonb,",
                f"  signoff = {sql_str(letter.get('signoff') or 'With love,')},",
                f"  sign_name = {sql_str(letter.get('signName') or 'Lorina')},",
                f"  scratchboard = {sql_str(board_json)}::jsonb,",
                f"  is_locked = {str(locked).lower()}",
                "from public.friends f",
                f"where l.friend_id = f.id and f.username = {sql_str(username)};",
                "",
            ]
        )

    lines.extend(
        [
            "-- ============================================================",
            "-- sanity checks",
            "-- ============================================================",
            "-- select key from public.app_settings order by key;",
            "-- select f.username, l.title, l.is_locked, jsonb_array_length(l.paragraphs) as paras",
            "-- from public.letters l join public.friends f on f.id = l.friend_id",
            "-- where f.username = 'adi';",
            "-- select * from public.get_letter_for('adi', 'MyBestBoyfriend');",
            "",
        ]
    )

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH.relative_to(ROOT)} ({len(people)} people)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
